African Fiction festival 2023
forLoop94/Conference_Page pull request #1
Opened 2023-04-20 12:39 UTC by forLoop94

1. I personalised the content of my page. I choose a topic(African Fiction Festival) that is different from the one in the original design.
2. I ensured the pages look almost identical to the original design. I made adjustments like text or image changes where necessary.
3. I built the Home and About pages.
4. Each of the two pages have mobile and desktop versions.
5. The home page has a link in the menu to the about page.
6. The logo in the header links to the home page.
7. When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
8. I implemented the mobile menu so it is consistent with the design (colors, typography, spacings, etc.).
9. The mobile menu has a close (X) button that closes the menu.
10. The section "Featured speakers" was created dynamically in JavaScript.
11. I stored the data about the speakers in a Javascript variable(array - stored in a separate file - speakersData.js) and used it during page loads to create the HTML for this section dynamically.
12. In my README file, I have given appropriate credit to Cindy Shin, the author.

2023-04-20 17:32 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @forLoop94 👋, 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

- [x] 💡    **[REQUIRED]** - According to the project requirements kindly record a video that meets the project documentation criteria as seen below:

![image](https://user-images.githubusercontent.com/78251927/233209547-3b242d2b-7b9d-409b-9675-0672697d12a1.png)

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 17:32 UTC, abdulhamiid commented on index.html
> +        </div>
Your design
![image](https://user-images.githubusercontent.com/78251927/233425576-742a68ab-dc6a-4ca6-a746-bf2cdf07065d.png)

Template
![image](https://user-images.githubusercontent.com/78251927/233425712-02a8b30a-9e42-4dab-85ed-f5be214eab3f.png)

According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md), it is important that we follow the [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including Colors, Typography, and Layout.

Kindly adjust the size of the cards in your styling so that all the cards have the same width so as to match the given template. 👍 


## Mobile
Your design
![image](https://user-images.githubusercontent.com/78251927/233433842-5202850b-890f-4d90-b50b-d451a4e5d338.png)

Template
![image](https://user-images.githubusercontent.com/78251927/233433603-c6f95b86-22e6-4834-8d21-5dfda284f5d5.png)

Kindly adjust the alignment of this section to match the original design. 🛠

2023-04-20 17:32 UTC, abdulhamiid commented on index.js
> +    const speakerDetails = arr[i];
Kindly remove the commented codes, let's not commit old pieces of code as inline comments. They will make your project look messy. If you need to review a previous version of your code, you can always use git history. 🤗💪

2023-04-20 17:32 UTC, abdulhamiid commented on styles.css
> +}
Your design
![image](https://user-images.githubusercontent.com/78251927/233431088-ba474121-e058-4f38-825d-e301ab35c864.png)

Kindly adjust the color of the line at the bottom of the `h1` text, let's use the exact same colors, for text, backgrounds, borders, etc, from the original design.

Basic color switch: `#272A31`, `#EC5242`, `#D3D3D3`

2023-04-20 17:32 UTC, abdulhamiid commented on index.js
> +    </div>`;
Template
![image](https://user-images.githubusercontent.com/78251927/233434245-0082b16d-921e-4daf-acc4-d17e4f406d59.png)

Your design
![image](https://user-images.githubusercontent.com/78251927/233435407-4327fdd0-29f7-4d6a-a95c-91cff975b69b.png)

Please kindly adjust the ratio of the images in your design `height/width` so that they do not look distorted and they fit well on the screen as the given template. .  🛠💪

2023-04-20 17:32 UTC, abdulhamiid commented on index2.html
> +    </footer>
- [x] Please let's add more spacing `padding-top/padding-bottom` to this section to match the original design. 

Your design
![image](https://user-images.githubusercontent.com/78251927/233442531-6f6ad283-db20-4e99-a35a-4f325de0ff7d.png)

Template
![image](https://user-images.githubusercontent.com/78251927/233443037-c31ed2b3-ca29-4069-86b3-623e632879c7.png)


- [x] Kindly align all the elements in this section to the center so as to match the template 🤝

Your design
![image](https://user-images.githubusercontent.com/78251927/233436018-5085144a-1b83-40bb-a8f1-73d7c256d7e2.png)

Template
![image](https://user-images.githubusercontent.com/78251927/233436107-6af59ab0-5a8d-4b43-b998-cc266ce000d3.png)

2023-04-20 17:32 UTC, abdulhamiid commented on index.html
> +          <li><a href="index2.html/#see-past-header">News</a></li>
Your design
![image](https://user-images.githubusercontent.com/78251927/233439302-c12ec445-8b60-4a35-a814-e221199d70a4.png)

Template
![image](https://user-images.githubusercontent.com/78251927/233439399-1ac66cee-04a2-49ec-9a68-39fee4c8643d.png)

Please kindly remove the image 👆  as it is not present in the original design. 👀👍

Part of the learning objective of this capstone project is to demonstrate our understanding of how to use medium-fidelity wireframes to create a UI. 🤗🛠


We can include a link to navigate back to the `Home page` in the nav list in the mobile version design to ensure the possibility to navigate between the pages of your website improving the user's experience. 🤗🛠

2023-04-20 17:32 UTC, abdulhamiid commented on index.html
> +      </div>
Kindly adjust the `Layout` of the content of this button to match the template. 👀🛠

Your design
![image](https://user-images.githubusercontent.com/78251927/233441786-081675ed-3df8-4d41-8a0b-edd12d9d094b.png)


Template
![image](https://user-images.githubusercontent.com/78251927/233441675-96bb8fac-8d73-495f-b684-74f0cfed7d1a.png)

2023-04-21 08:27 UTC, forLoop94 commented
All issues resolved. Thank you

2023-04-21 09:29 UTC, OyePriscilla approved these changes
Hi @forLoop94 👏 👏 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Use Flexbox to place elements in the page ✔️
Use JavaScript to manipulate DOM elements ✔️
Use JavaScript events ✔️
Use objects to store and access data ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 06:52 UTC, forLoop94 commented
Thank you @OyePriscilla

2023-04-22 06:52 UTC, merged